### ISSUE TITLE
source Code 

### ISSUE THREAD

**Issue by vaddekrishn** [vaddekrishn/CIS-634#7] opened 2022-10-27 21:42 UTC
Done testing the login view and the database of the application for users names and passwords working good able to create new user and password. The UI able to re-adject according to the screen. The code is cleaned. Need the source code for the admin page

**Comment by savanrao** [comment] 2022-10-31 18:57
Is the testing done??

**Comment by vaddekrishn** [comment] 2022-10-31 20:37
yes Sava, I will send you the clean code ASAP !

**Comment by savanrao** [comment] 2022-11-01 20:07
I guess the issue is resolved, so i will be closing it

**Closed by savanrao** 2022-11-01 20:07 UTC

**Comment by vaddekrishn** [comment] 2022-11-02 05:14
Sava can you give me the update on the elements we discussed on the zoom call please.

**Comment by savanrao** [comment] 2022-11-02 05:20
My name is not sava 🤦🏻

**Comment by vaddekrishn** [comment] 2022-11-02 05:23
😅 sava_n

**Comment by savanrao** [comment] 2022-11-02 05:24
And I have sent all the updates on the email can u check
